/**
 * `ahtml init` — the 10-minute on-ramp (ROADMAP Feature 3, TASKS.md T3.1–T3.3).
 *
 * Detects the framework, wires the adapter files, generates a starter
 * snapshot from the homepage via the universal extractor, and reports the
 * doctor command as the exit check.
 *
 * Design: `planInit()` is PURE — it computes the full `FileChange[]` without
 * touching disk — and `applyPlan()` writes it. That split is what makes
 * idempotence (plan diff == empty → exit 0, no writes) and the unsupported-
 * framework guarantee (detect fails → nothing was ever written) testable.
 */
import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { validate } from '@ahtmljs/schema';
import { createExtractor, pageFromHtml } from '@ahtmljs/extract';

export type Framework = 'next' | 'vite' | 'hono' | 'astro' | 'sveltekit';
export const SUPPORTED: Framework[] = ['next', 'vite', 'hono', 'astro', 'sveltekit'];
const MANUAL_SETUP_DOC = 'https://github.com/DibbayajyotiRoy/AHTML#quickstart';

export interface FileChange {
  /** Repo-relative path inside the target project. */
  path: string;
  content: string;
}

export interface InitPlan {
  framework: Framework;
  changes: FileChange[];       // files whose current content differs (or absent)
  unchanged: string[];         // planned files already exactly in place
  dependency: string;          // the adapter package to install
  dependencyAlreadyDeclared: boolean;
}

/* -------------------------------------------------------------------------- */
/* T3.1 — framework detection                                                 */
/* -------------------------------------------------------------------------- */

/**
 * Detect the target's framework from package.json dependencies + config
 * files. Order matters: SvelteKit and Astro apps also depend on vite, so
 * the more specific frameworks are checked first.
 */
export function detectFramework(dir: string): Framework | null {
  const pkgPath = join(dir, 'package.json');
  let deps: Record<string, string> = {};
  if (existsSync(pkgPath)) {
    try {
      const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'));
      deps = { ...pkg.dependencies, ...pkg.devDependencies };
    } catch {
      /* malformed package.json — fall through to config-file detection */
    }
  }
  const hasConfig = (...names: string[]) => names.some((n) => existsSync(join(dir, n)));

  if (deps['@sveltejs/kit'] || hasConfig('svelte.config.js', 'svelte.config.ts')) return 'sveltekit';
  if (deps['astro'] || hasConfig('astro.config.mjs', 'astro.config.ts', 'astro.config.js')) return 'astro';
  if (deps['next'] || hasConfig('next.config.js', 'next.config.mjs', 'next.config.ts')) return 'next';
  if (deps['hono']) return 'hono';
  if (deps['vite'] || hasConfig('vite.config.ts', 'vite.config.js', 'vite.config.mjs')) return 'vite';
  return null;
}

/* -------------------------------------------------------------------------- */
/* wiring templates — canonical per-adapter layouts from each README          */
/* -------------------------------------------------------------------------- */

const LIB_AHTML = `import { snapshot } from '@ahtmljs/schema';
import starter from './ahtml-starter.json' assert { type: 'json' };

/**
 * Build the AHTML snapshot for a path. Generated by \`ahtml init\`:
 * the homepage serves the extracted starter snapshot; add your own
 * routes (products, docs, ...) as your data layer allows.
 */
export async function buildSnapshot(segments: string[], req: Request) {
  if (segments.length === 0) {
    return { ...starter, url: new URL('/', req.url).toString() };
  }
  return null;
}
`;

function wiring(framework: Framework): FileChange[] {
  switch (framework) {
    case 'next':
      return [
        { path: 'lib/ahtml.ts', content: LIB_AHTML },
        {
          path: 'app/ahtml/[[...path]]/route.ts',
          content:
            "import { createAHTMLRoute } from '@ahtmljs/next/handler';\n" +
            "import { buildSnapshot } from '../../../lib/ahtml';\n\n" +
            'export const { GET, HEAD } = createAHTMLRoute(buildSnapshot);\n',
        },
        {
          path: 'app/.well-known/ahtml.json/route.ts',
          content:
            "import { createWellKnownRoute } from '@ahtmljs/next/well-known';\n" +
            'export const { GET } = createWellKnownRoute();\n',
        },
        {
          path: 'app/llms.txt/route.ts',
          content:
            "import { createLlmsTxtRoute } from '@ahtmljs/next/llms-txt';\n" +
            'export const { GET } = createLlmsTxtRoute();\n',
        },
        {
          path: 'app/ahtml/mcp.json/route.ts',
          content:
            "import { createMcpRoute } from '@ahtmljs/next/mcp';\n" +
            "import { buildSnapshot } from '../../../lib/ahtml';\n" +
            'export const { GET } = createMcpRoute(buildSnapshot);\n',
        },
      ];
    case 'astro':
      return [
        { path: 'src/lib/ahtml.ts', content: LIB_AHTML },
        {
          path: 'src/ahtml-integration.mjs',
          content:
            "import { ahtml } from '@ahtmljs/astro';\n" +
            "import { buildSnapshot } from './lib/ahtml';\n\n" +
            '// Add to astro.config: integrations: [ahtmlIntegration]\n' +
            'export const ahtmlIntegration = ahtml({ snapshotBuilder: buildSnapshot });\n',
        },
      ];
    case 'sveltekit':
      return [
        { path: 'src/lib/ahtml.ts', content: LIB_AHTML },
        {
          path: 'src/hooks.server.ahtml.ts',
          content:
            "import { ahtmlHandle } from '@ahtmljs/sveltekit';\n" +
            "import { buildSnapshot } from '$lib/ahtml';\n\n" +
            '// Compose into src/hooks.server.ts: export const handle = ahtmlHandle({...})\n' +
            "export const handle = ahtmlHandle({ site: process.env.SITE_URL ?? 'http://localhost:5173', snapshotBuilder: buildSnapshot });\n",
        },
      ];
    case 'vite':
      return [
        { path: 'lib/ahtml.ts', content: LIB_AHTML },
        {
          path: 'ahtml.vite.mjs',
          content:
            "import { ahtml } from '@ahtmljs/vite';\n" +
            "import { buildSnapshot } from './lib/ahtml';\n\n" +
            '// Add to vite.config plugins: [ahtmlPlugin]\n' +
            "export const ahtmlPlugin = ahtml({ site: process.env.SITE_URL ?? 'http://localhost:5173', buildSnapshot });\n",
        },
      ];
    case 'hono':
      return [
        { path: 'lib/ahtml.ts', content: LIB_AHTML },
        {
          path: 'ahtml.hono.mjs',
          content:
            "import { mountAHTML } from '@ahtmljs/hono';\n" +
            "import { buildSnapshot } from './lib/ahtml';\n\n" +
            '// Call mountAHTML(app, ...) after creating your Hono app.\n' +
            "export const mount = (app) => mountAHTML(app, { site: process.env.SITE_URL ?? 'http://localhost:3000', snapshotBuilder: buildSnapshot });\n",
        },
      ];
  }
}

const ADAPTER_PACKAGE: Record<Framework, string> = {
  next: '@ahtmljs/next',
  vite: '@ahtmljs/vite',
  hono: '@ahtmljs/hono',
  astro: '@ahtmljs/astro',
  sveltekit: '@ahtmljs/sveltekit',
};

/* -------------------------------------------------------------------------- */
/* starter snapshot from the homepage (universal extractor)                   */
/* -------------------------------------------------------------------------- */

export function starterSnapshot(siteUrl: string, homepageHtml: string): Record<string, unknown> {
  const extraction = createExtractor().extract(pageFromHtml(siteUrl, homepageHtml));
  const snap: Record<string, unknown> = {
    ahtml: '0.1',
    url: siteUrl,
    fetched_at: new Date().toISOString(),
    ttl: 300,
    page_type: extraction.page_type ?? 'home',
    policy: { agents_welcome: true },
    entities: extraction.entities,
    actions: extraction.actions,
  };
  const errors = validate(snap as never).filter((i) => i.severity === 'error');
  if (errors.length) {
    throw new Error(`starter snapshot failed validation: ${JSON.stringify(errors)}`);
  }
  return snap;
}

/* -------------------------------------------------------------------------- */
/* T3.2/T3.3 — plan + apply                                                   */
/* -------------------------------------------------------------------------- */

export interface InitOptions {
  /** Homepage HTML for starter extraction (tests / --html file). Without it
   *  the starter snapshot is an empty-but-valid home snapshot. */
  homepageHtml?: string;
  siteUrl?: string;
}

export function planInit(dir: string, opts: InitOptions = {}): InitPlan {
  const framework = detectFramework(dir);
  if (!framework) {
    throw new UnsupportedFramework(
      `ahtml init: no supported framework detected in ${dir}.\n` +
        `Supported: ${SUPPORTED.join(', ')}.\n` +
        `Manual setup: ${MANUAL_SETUP_DOC}\n`,
    );
  }
  const siteUrl = opts.siteUrl ?? 'http://localhost:3000/';
  const starter = starterSnapshot(siteUrl, opts.homepageHtml ?? '<html><body></body></html>');
  // Deterministic content for idempotence: reuse the previously generated
  // fetched_at when the starter file already exists and is otherwise equal.
  const starterPath = framework === 'next' ? 'lib/ahtml-starter.json' : 'src/lib/ahtml-starter.json';
  const existing = join(dir, starterPath);
  if (existsSync(existing)) {
    try {
      const prev = JSON.parse(readFileSync(existing, 'utf8'));
      const a = { ...starter, fetched_at: '' };
      const b = { ...prev, fetched_at: '' };
      if (JSON.stringify(a) === JSON.stringify(b)) starter.fetched_at = prev.fetched_at;
    } catch {
      /* rewrite malformed starter */
    }
  }

  const planned: FileChange[] = [
    ...wiring(framework),
    { path: starterPath, content: JSON.stringify(starter, null, 2) + '\n' },
  ];

  const changes: FileChange[] = [];
  const unchanged: string[] = [];
  for (const f of planned) {
    const target = join(dir, f.path);
    if (existsSync(target) && readFileSync(target, 'utf8') === f.content) unchanged.push(f.path);
    else changes.push(f);
  }

  const dependency = ADAPTER_PACKAGE[framework];
  let dependencyAlreadyDeclared = false;
  try {
    const pkg = JSON.parse(readFileSync(join(dir, 'package.json'), 'utf8'));
    dependencyAlreadyDeclared = Boolean(pkg.dependencies?.[dependency]);
  } catch {
    /* no package.json — dependency must be added */
  }

  return { framework, changes, unchanged, dependency, dependencyAlreadyDeclared };
}

export class UnsupportedFramework extends Error {}

export function applyPlan(dir: string, plan: InitPlan): void {
  for (const f of plan.changes) {
    const target = join(dir, f.path);
    mkdirSync(dirname(target), { recursive: true });
    writeFileSync(target, f.content);
  }
  if (!plan.dependencyAlreadyDeclared) {
    const pkgPath = join(dir, 'package.json');
    const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'));
    pkg.dependencies = { ...pkg.dependencies, [plan.dependency]: '^1.0.0' };
    writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n');
  }
}

/* -------------------------------------------------------------------------- */
/* CLI entry                                                                  */
/* -------------------------------------------------------------------------- */

export async function runInit(
  dir: string,
  flags: { html?: string; site?: string } = {},
): Promise<number> {
  let plan: InitPlan;
  try {
    plan = planInit(dir, {
      homepageHtml: flags.html ? readFileSync(flags.html, 'utf8') : undefined,
      siteUrl: flags.site,
    });
  } catch (err) {
    if (err instanceof UnsupportedFramework) {
      process.stderr.write(err.message);
      return 1;
    }
    throw err;
  }

  if (plan.changes.length === 0 && plan.dependencyAlreadyDeclared) {
    process.stdout.write(`ahtml init: ${plan.framework} project already wired — nothing to do.\n`);
    return 0;
  }

  applyPlan(dir, plan);
  process.stdout.write(
    `ahtml init: detected ${plan.framework}\n` +
      plan.changes.map((c) => `  wrote ${c.path}\n`).join('') +
      (plan.dependencyAlreadyDeclared ? '' : `  added dependency ${plan.dependency}\n`) +
      `\nNext steps:\n  1. npm install\n  2. npm run dev\n  3. npx @ahtmljs/cli doctor http://localhost:3000   (exit check)\n`,
  );
  return 0;
}
