/**
 * Server-side render of the live AHTML snapshot for this page.
 * The text below is generated by the live toCompact() call against the
 * same homeSnapshot() the /ahtml route serves. Same code path. No
 * separate generation for the demo.
 */

import { toCompact } from '@ahtmljs/schema';
import { homeSnapshot } from '@/lib/snapshots';
import SnapshotPre from './SnapshotPre';

export default function AgentView() {
  const snap = homeSnapshot('https://github.com/DibbayajyotiRoy/AHTML');
  const compact = toCompact(snap);
  const compactBytes = Buffer.byteLength(compact, 'utf8');
  // Representative HTML byte count for this page's hero + dogfood strip,
  // measured against a production build. See /examples/benchmark for the
  // reproducible numbers across the full corpus.
  const htmlBytesEstimate = 28_400;
  const ratio = htmlBytesEstimate / compactBytes;

  return (
    <section className="agent-view">
      <div className="container">
        <div className="eyebrow">Live · agent view of this page</div>
        <h2 style={{ marginBottom: 20 }}>This is what the agent actually reads.</h2>
        <p className="lede">
          Same page. Same content. One serialization for browsers, one for agents.
          Generated by the live{' '}
          <code className="inline" style={inlineCodeStyle}>toCompact()</code> in{' '}
          <code className="inline" style={inlineCodeStyle}>@ahtmljs/schema</code>.
        </p>
        <SnapshotPre compact={compact} />
        <div className="compare">
          <div>
            <h4>This page as HTML</h4>
            <div className="bignum">
              ~{htmlBytesEstimate.toLocaleString()}<sup> bytes</sup>
            </div>
            <div style={{ marginTop: 4, fontSize: 13, opacity: 0.6, fontFamily: 'var(--font-mono)' }}>
              The chrome an agent has to skim past.
            </div>
          </div>
          <div>
            <h4>This snapshot</h4>
            <div className="bignum accent">
              {compactBytes.toLocaleString()}<sup> bytes</sup>
            </div>
            <div style={{ marginTop: 4, fontSize: 13, opacity: 0.7, fontFamily: 'var(--font-mono)', color: 'var(--accent)' }}>
              {ratio.toFixed(1)}× smaller, and it includes typed actions HTML never had.
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

const inlineCodeStyle = {
  background: 'rgba(255,255,255,0.06)',
  borderColor: 'rgba(255,255,255,0.2)',
  color: 'inherit' as const,
};
